[project]
name = "mazpop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jkolberg", email = "jkolberg@psrc.org" }
]
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.4",
    "iteround>=1.0.4",
    "osmnx>=2.1.1",
    "populationsim>=0.10.0",
    "pypyr>=5.9.1",
    "requests>=2.34.2",
    "us>=3.2.0",
]

[project.scripts]
mazpop = "mazpop.cli.main:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
